Change cluster-admin role to `ml-pipeline-persistenceagent` for the pipeline/persistent-agent sa
kubeflow/manifests pull request #1712
Opened 2021-01-12 21:22 UTC by 4n4nd

**Which issue is resolved by this Pull Request:**
Resolves #1711 

**Description of your changes:**
Change clusterrole given to `ml-pipeline-persistenceagent` serviceaccount

**Checklist:**
- [ ] Unit tests have been rebuilt: 
    1. `cd manifests/tests`
    2. `make generate-changed-only`
    3. `make test`

2021-01-12 21:24 UTC, PatrickXYS requested changes
Please sign CLA and generate manifests. Otherwise the PR won't pass tests

2021-01-12 21:26 UTC, 4n4nd commented
@googlebot I signed it!

2021-01-12 21:28 UTC, PatrickXYS commented
/ok-to-test

2021-01-12 21:35 UTC, 4n4nd commented
@PatrickXYS should i still update the manifests?

2021-01-12 22:00 UTC, PatrickXYS commented
> @PatrickXYS should i still update the manifests?

Yes you still need to generate manifests for test data

2021-01-13 14:41 UTC, 4n4nd commented
/retest

2021-01-13 15:46 UTC, 4n4nd commented
I am not sure how to fix this issue:
```
INFO|2021-01-12T23:07:19|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|28| Workflow kubeflow-manifests-presubmit-e2e-1712-fd00172-1360-dcfd in namespace kubeflow-test-infra; phase=Running
INFO|2021-01-12T23:07:49|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|28| Workflow kubeflow-manifests-presubmit-unit-1712-fd00172-1360-4864 in namespace kubeflow-test-infra; phase=Failed
INFO|2021-01-12T23:07:49|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|28| Workflow kubeflow-manifests-presubmit-e2e-1712-fd00172-1360-dcfd in namespace kubeflow-test-infra; phase=Running
INFO|2021-01-12T23:08:19|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|28| Workflow kubeflow-manifests-presubmit-unit-1712-fd00172-1360-4864 in namespace kubeflow-test-infra; phase=Failed
INFO|2021-01-12T23:08:19|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|28| Workflow kubeflow-manifests-presubmit-e2e-1712-fd00172-1360-dcfd in namespace kubeflow-test-infra; phase=Running
INFO|2021-01-12T23:08:49|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|48| Parsing ApiException body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
INFO|2021-01-12T23:08:49|/src/kubeflow/testing/py/kubeflow/testing/argo_client.py|60| ApiException code=401 
```

2021-01-13 16:30 UTC, PatrickXYS commented
I doubt if your PR messed something, 2209 file change is too large for one single line of actual code change.

2021-01-13 17:24 UTC, 4n4nd commented
> 2209 file change is too large for one single line of actual code change.

I thought so too, but that's what changed when I ran `make generate-changed-only`

2021-01-13 17:45 UTC, PatrickXYS commented
https://github.com/kubeflow/manifests/blob/master/pipeline/persistent-agent/base/clusterrole.yaml

This is the clusterrole for persistent-agent, no sure where do you get this clusterrole `ml-pipeline-persistentagent`

2021-01-13 18:00 UTC, 4n4nd commented
> https://github.com/kubeflow/manifests/blob/master/pipeline/persistent-agent/base/clusterrole.yaml
> 
> This is the clusterrole for persistent-agent, no sure where do you get this clusterrole `ml-pipeline-persistentagent`

There's a nameprefix in the kustomization which adds the `ml-pipeline-` prefix: https://github.com/kubeflow/manifests/blob/master/pipeline/persistent-agent/base/kustomization.yaml#L3

2021-01-13 22:24 UTC, PatrickXYS commented
I'll revisit afterwards, it should be simple instead of 2209 files change

2021-01-13 23:51 UTC, PatrickXYS commented
@4n4nd I ran it on my local with one line change of code, `make generate-change-only` only changes one single test file. 

What I would suggest is:

1. Start with a fresh environment with master branch of kubeflow/manifests
2. Make sure you have kustomize <3.2
3. Then generate tests to see if anything wrong

2021-01-14 03:24 UTC, 4n4nd commented
/retest

2021-01-14 04:22 UTC, 4n4nd commented
> @4n4nd I ran it on my local with one line change of code, `make generate-change-only` only changes one single test file. 
> 
> 
> 
> What I would suggest is:
> 
> 
> 
> 1. Start with a fresh environment with master branch of kubeflow/manifests
> 
> 2. Make sure you have kustomize <3.2
> 
> 3. Then generate tests to see if anything wrong

kustomize v3.2.2 worked for this 👍

2021-01-14 05:15 UTC, PatrickXYS commented
/lgtm
/approve

Thanks!

2021-01-14 05:17 UTC, merged