add kfp-tekton manifests
kubeflow/manifests pull request #1824
Opened 2021-04-08 21:41 UTC by Tomcli

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Add manifests from [kfp-tekton](https://github.com/kubeflow/kfp-tekton)

The image tags will be updated when kfp-tekton is able to rebase on top of kfp 1.5.0.

These manifests will also be part of kfp-tekton repo when we cut the official release.

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 3.2.1**
    1. `make generate-changed-only`
    2. `make test`

2021-04-08 21:43 UTC, Tomcli commented
/cc @moficodes @pvaneck @animeshsingh

2021-04-08 21:45 UTC, moficodes commented
@Tomcli is this updated with the latest images?

2021-04-08 21:48 UTC, moficodes approved these changes
/lgtm

2021-04-08 21:51 UTC, Tomcli commented
@moficodes not the latest image. These manifests currently has the 0.8.0-rc0 pre-release images which you can test the kubeflow deployment with them.

2021-04-08 22:45 UTC, moficodes commented on apps/kfp-tekton/upstream/base/installs/multi-user/kustomization.yaml
> +- ../../cache-deployer/cluster-scoped
This will cause conflict.

2021-04-08 22:46 UTC, moficodes commented on apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml
> +  - cluster-scoped
This is duplicate.

we should choose one.

2021-04-08 22:47 UTC, moficodes requested changes
there is a conflict in apps/kfp-tekton/upstream/base/pipeline/kustomization.yaml

we should remove `cluster-scoped` as a base

2021-04-08 23:14 UTC, moficodes commented on apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
> +  - cluster-scoped
duplicate

2021-04-08 23:15 UTC, moficodes commented on apps/kfp-tekton/upstream/base/installs/multi-user/kustomization.yaml
> +- ../../cache-deployer/cluster-scoped
duplicate. we should remove one.

2021-04-08 23:17 UTC, moficodes commented on apps/kfp-tekton/upstream/base/cache-deployer/kustomization.yaml
> +  - cluster-scoped
i think removing this one is going to be best as it matches argos manifest.

2021-04-09 00:46 UTC, pvaneck commented
Is the kustomize entry-point the same as pipelines? i.e.

```
kustomize build --load_restrictor=none apps/kfp-tekton/upstream/env/platform-agnostic-multi-user | kubectl apply -f -
```

2021-04-09 01:14 UTC, moficodes commented
@pvaneck yes.

2021-04-09 19:48 UTC, yanniszark commented
@Tomcli thanks a lot for preparing this PR! I wanted to give a heads-up that the process we follow for manifests is to copy a subdirectory of the upstream app repo (in this case kfp-tekton) to the manifests repo (in this case under `apps/kfp-tekton/upstream`). Maybe you have done this already, just FYI.

2021-04-09 20:03 UTC, Tomcli commented
Thanks @yanniszark, do we have to update any script in the kubeflow/manifests to pull the manifests from kfp-tekton repo? We can close this PR since the kfp-tekton repo has the same manifests as this PR.

2021-04-13 19:41 UTC, yanniszark commented
@Tomcli we are syncing manually right now. Could you please provide me with the desired revision for kfp-tekton?

2021-04-13 23:28 UTC, Tomcli commented
@yanniszark Here is the manifests from kfp-tekton v0.8.0-rc0 tag. https://github.com/kubeflow/kfp-tekton/tree/v0.8.0-rc0/manifests/kustomize

We will cut an official v0.8.0 release that's based on the upcoming KFP 1.5.0 release, but v0.8.0-rc0 is close enough since it was based on the KFP 1.5.0-RC2 release which is in the current kubeflow/manifests.

2021-04-14 13:57 UTC, yanniszark commented
@Tomcli please see: https://github.com/kubeflow/manifests/pull/1843

2021-04-14 15:34 UTC, Tomcli commented
/close

2021-04-14 15:34 UTC, closed without merging