Add kuberay aggregated-roles
kubeflow/manifests pull request #2675
Opened 2024-04-08 09:52 UTC by alex-treebeard

**Which issue is resolved by this Pull Request:**
Resolves #2671

**Description of your changes:**

Adds aggregated roles as discussed in https://github.com/kubeflow/manifests/issues/2671

**Checklist:**
- [ ] Unit tests pass:
  **Make sure you have installed kustomize == 5.2.1+**
    1. `make generate-changed-only`
    2. `make test`

@juliusvonkohout 

Thanks for the guidance on the issue.

Ray + Istio warrants an offline chat IMO. I've also tried it myself and am unclear about the UX/security implications of those three levels of istio integration. I'm also conscious that if we switch to ambient mesh that will change this also (as Ray cluster's sidecar would fail if it ran before the istio sidecar).

Please let me know if any naming conventions etc need to be followed in the diff - this is ready for review.

2024-04-09 07:16 UTC, juliusvonkohout requested changes
Please try to structure it like https://github.com/kubeflow/manifests/blob/master/apps/katib/upstream/installs/katib-with-kubeflow/kubeflow-katib-roles.yaml

2024-04-10 16:28 UTC, alex-treebeard commented
sure, i've
- indented lists (and used yaml not json syntax)
- ordered object keys
- added leading '---'

just let me know if you meant any semantic changes

2024-04-15 06:48 UTC, juliusvonkohout commented
/lgtm
/approve

thank you for your contribution.

2024-04-15 06:49 UTC, juliusvonkohout approved these changes

2024-04-15 06:49 UTC, merged